default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friendly_reader_be_development
  username: postgres # You can specify your username here if needed
  password: password # This can be an environment variable or hardcoded for dev
  host: localhost
  port: 5432

test:
  <<: *default
  database: friendly_reader_be_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: friendly_reader_be_production
    username: friendly_reader_be
    password: <%= ENV["FRIENDLY_READER_BE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: friendly_reader_be_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: friendly_reader_be_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: friendly_reader_be_production_cable
    migrations_paths: db/cable_migrate
